name: Update Submodules-wlj

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitbutler_swiftMain0225
        uses: actions/checkout@v4.1.6
        with:
          ref: "gitbutler/swiftMain0225"
          submodules: "recursive"
  
      - name: Update submodule gitbutler_swiftMain0225
        id: apple-arm64e
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi
  
      - name: Push changes gitbutler_swiftMain0225
        if: ${{ steps.apple-arm64e.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gitbutler/swiftMain0225
